In [1]:
import pandas as pd
!pip install xlrd

Collecting xlrd
  Downloading https://files.pythonhosted.org/packages/07/e6/e95c4eec6221bfd8528bcc4ea252a850bffcc4be88ebc367e23a1a84b0bb/xlrd-1.1.0-py2.py3-none-any.whl (108kB)
Installing collected packages: xlrd
Successfully installed xlrd-1.1.0

In [0]:
import numpy as np

In [2]:
import re
energy=pd.read_excel("https://storage.googleapis.com/py_ml_datasets/Energy%20Indicators.xls")
energy.head();
energy=energy.dropna(thresh=4)
energy=energy.dropna(axis=1)
energy.columns=['Country', 'Energy Supply', 'Energy Supply per Capita', '% Renewable']
energy=energy.drop(7)
energy[energy[:]=='...']=np.NaN
energy["Energy Supply"]=energy["Energy Supply"]*1000000

dict_data={"Republic of Korea": "South Korea",
"United States of America": "United States",
"United Kingdom of Great Britain and Northern Ireland": "United Kingdom",
"China, Hong Kong Special Administrative Region": "Hong Kong"}

for i in energy["Country"].values:
  energy["Country"][energy["Country"].values==i]=i.split(" (")[0]

for i in energy["Country"].values:
  energy["Country"][energy["Country"].values==i]=re.compile(r'[^\D]+').sub('', i)

for i in dict_data.items():
  energy["Country"][energy["Country"].values==i[0]]=i[1]

NameError: name 'np' is not defined

In [213]:
GDP=pd.read_csv('https://storage.googleapis.com/py_ml_datasets/world_bank.csv')
GDP=GDP.drop([0,1,2])
dict_data={"Korea, Rep.": "South Korea",
"Iran, Islamic Rep.": "Iran",
"Hong Kong SAR, China": "Hong Kong"}
for i in dict_data.items():
  GDP["Data Source"][GDP["Data Source"].values==i[0]]=i[1]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys

In [0]:
ScimEn=pd.read_excel("https://storage.googleapis.com/py_ml_datasets/scimagojr-3.xlsx")

In [221]:
ScimEn=ScimEn[ScimEn['Rank']<=15]
GDP2=pd.concat([GDP['Data Source'],GDP.loc[:,'Unnamed: 50':'Unnamed: 59']],axis=1)
GDP2.columns=['Country Name', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']
GDP2=GDP2.drop(3)
energy.head()

           Country Energy Supply Energy Supply per Capita % Renewable
9          Andorra       9000000                      121     88.6957
16     Afghanistan     321000000                       10     78.6693
17         Albania     102000000                       35         100
18         Algeria    1959000000                       51     0.55101
19  American Samoa           NaN                      NaN    0.641026

In [241]:
def answer_one(): 
  df=pd.merge(ScimEn,GDP2,left_on='Country',right_on='Country Name')
  df=pd.merge(df,energy,left_on='Country',right_on='Country')
  df.drop("Country Name",axis=1,inplace=True)
  df=df.set_index('Country')
  return df

answer_one()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Energy Supply,Energy Supply per Capita,% Renewable
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,127191000000,93,19.7549
United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,90838000000,286,11.571
Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,18984000000,149,10.2328
United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,7920000000,124,10.6005
Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,30709000000,214,17.2887
Canada,6,17899,17620,215003,40930,12.01,149,1.564469e+12,1.596740e+12,1.612713e+12,1.565145e+12,1.613406e+12,1.664087e+12,1.693133e+12,1.730688e+12,1.773486e+12,1.792609e+12,10431000000,296,61.9454
Germany,7,17027,16831,140566,27426,8.26,126,3.332891e+12,3.441561e+12,3.478809e+12,3.283340e+12,3.417298e+12,3.542371e+12,3.556724e+12,3.567317e+12,3.624386e+12,3.685556e+12,13261000000,165,17.9015
India,8,15005,14841,128763,37209,8.58,115,1.265894e+12,1.374865e+12,1.428361e+12,1.549483e+12,1.708459e+12,1.821872e+12,1.924235e+12,2.051982e+12,2.200617e+12,2.367206e+12,33195000000,26,14.9691
France,9,13153,12973,130632,28601,9.93,114,2.607840e+12,2.669424e+12,2.674637e+12,2.595967e+12,2.646995e+12,2.702032e+12,2.706968e+12,2.722567e+12,2.729632e+12,2.761185e+12,10597000000,166,17.0203
South Korea,10,11983,11923,114675,22595,9.57,104,9.410199e+11,9.924316e+11,1.020510e+12,1.027730e+12,1.094499e+12,1.134796e+12,1.160809e+12,1.194429e+12,1.234340e+12,1.266580e+12,11007000000,221,2.27935
Italy,11,10964,10794,111850,26661,10.20,106,2.202170e+12,2.234627e+12,2.211154e+12,2.089938e+12,2.125185e+12,2.137439e+12,2.077184e+12,2.040871e+12,2.033868e+12,2.049316e+12,6530000000,109,33.6672
Spain,12,9428,9330,123336,23964,13.08,115,1.414823e+12,1.468146e+12,1.484530e+12,1.431475e+12,1.431673e+12,1.417355e+12,1.380216e+12,1.357139e+12,1.375605e+12,1.419821e+12,4923000000,106,37.9686
Iran,13,8896,8819,57470,19125,6.46,72,3.895523e+11,4.250646e+11,4.289909e+11,4.389208e+11,4.677902e+11,4.853309e+11,4.532569e+11,4.445926e+11,4.639027e+11,NaN,9172000000,119,5.70772
Australia,14,8831,8725,90765,15606,10.28,107,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12,5386000000,231,11.8108
Brazil,15,8668,8596,60702,14396,7.00,86,1.845080e+12,1.957118e+12,2.056809e+12,2.054215e+12,2.208872e+12,2.295245e+12,2.339209e+12,2.409740e+12,2.412231e+12,2.319423e+12,12149000000,59,69.648

In [0]:
def answer_two():
    
    return